### ISSUE TITLE
OperationalError: (OperationalError) database is locked 

### ISSUE THREAD

**Issue by stefanosgeo** [opencast/pyCA#124]
Hi,

python version Python 2.7.9 
for the upgrade I copied the following folders

pyca/
setup.py
start.sh

Pi has a crontab for every reboot to automatically start the pyca service
at reboot       `cd /home/pi/pyCA/ && ./start.sh > /home/pi/logs/cronlog 2>&1`

There is no status update in OC server and after upgrade to 2.1 I get the following errors

```
pyca.schedule:106:control_loop()] [INFO] No scheduled recording
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "pyca/agentstate.py", line 38, in run
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "pyca/ingest.py", line 144, in run
    control_loop()
  File "pyca/agentstate.py", line 23, in control_loop
    set_service_status(Service.AGENTSTATE, ServiceStatus.BUSY)
  File "pyca/utils.py", line 187, in set_service_status
    control_loop()
  File "pyca/ingest.py", line 121, in control_loop
    set_service_status(Service.INGEST, ServiceStatus.IDLE)
  File "pyca/utils.py", line 186, in set_service_status
    if s.count():
    s.update({'status': status})
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2796, in update
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2640, in count
    update_op.exec_()
    return self.from_self(col).scalar()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2426, in scalar
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 897, in exec_
    ret = self.one()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2395, in one
    ret = list(self)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2438, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2453, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    self._do_exec()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 995, in _do_exec
    update_stmt, params=self.query._params)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 991, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
compiled_sql, distilled_params
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
    context)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    exc_info
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
    context)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) database is locked u'SELECT count(*) AS count_1 \nFROM (SELECT service_states.type AS service_states_type, service_states.status AS service_states_status \nFROM service_states \nWHERE service_states.type = ?) AS anon_1' (3,)
OperationalError: (OperationalError) database is locked u'UPDATE service_states SET status=? WHERE service_states.type = ?' (3, 1)
```

Stefanos

*EDIT(Lars): Added code blocks*

**Comment by lkiesow** [comment]
- Does the error persist on restarts?
- Can you give us the full log (or at least a bit more around the error) to see what else happens
- Does your user have proper permissions on the database?
- Does the error persists when you remove the database file?

[Note for myself (possibly related)](http://stackoverflow.com/questions/13895176/sqlalchemy-and-sqlite-database-is-locked)

**Comment by stefanosgeo** [comment]
Ok,

strange but after two restarts it worked! Also ingest is now working!

Thanks
