### ISSUE TITLE
Umlaute in Titel und Beschreibung führen zu pycurl.error: (0, '') - Opencast 2.0

### ISSUE THREAD

**Issue by b-bremer** [opencast/pyCA#24]
Zum Reproduzieren einfach eine Aufzeichnung mit dem Titel "Ümlaut Täst" anlegen.

und pyCA mit python3 starten

Der Fehler:
2016-01-31 12:41:06 ERROR    [ca.py:257:start_capture()] Something went wrong during the upload
2016-01-31 12:41:06 ERROR    [ca.py:258:start_capture()] Traceback (most recent call last):
  File "/home/benjamin/Coding/Repos/pyCA/pyca/ca.py", line 255, in start_capture
    workflow_config)
  File "/home/benjamin/Coding/Repos/pyCA/pyca/ca.py", line 336, in ingest
    mediapackage = http_request(service + '/addDCCatalog', fields)
  File "/home/benjamin/Coding/Repos/pyCA/pyca/ca.py", line 293, in http_request
    curl.setopt(curl.HTTPPOST, post_data)
pycurl.error: (0, '')

Eine mögliche Lösung:
Muss aber noch testen ob und was dadurch kaputt geht.

```
    with open('%s/episode.xml' % recording_dir, 'r') as episodefile:
        dublincore = episodefile.read().encode('utf8', 'ignore')
```

und

```
    with open('%s/series.xml' % recording_dir, 'r') as seriesfile:
        dublincore = seriesfile.read().encode('utf8', 'ignore')
```

**Comment by b-bremer** [comment]
Die mögliche Lösung funktioniert.

Soll ich einen Pullrequest stellen?

**Comment by b-bremer** [comment]
#25 fixes it
