### ISSUE TITLE
Unicode error in start_capture

### ISSUE THREAD

**Issue by lkiesow** [opencast/pyCA#45]
```
2016-11-20 23:25:02 ERROR    [ca.py:395:safe_start_capture()] Start capture failed
2016-11-20 23:25:02 ERROR    [ca.py:396:safe_start_capture()] Traceback (most recent call last):
  File "pyca/ca.py", line 393, in safe_start_capture
    return start_capture(event)
  File "pyca/ca.py", line 264, in start_capture
    f.write(value)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 506-510: ordinal not in range(128)
```

**Comment by pascalzurek** [comment]
I've had that issue with another piece of software some weeks ago. This is most likely due to LANG not being set (i. e. when running as a service/daemon, "env LANG=de_DE.UTF-8" should be set).

**Comment by lkiesow** [comment]
No, pyCA just needs to decode the strings using `utf-8` rather than `ascii` as encoding. It's an issue we have fixed at some places already. This is more to remind me that it needs to be fixed here as well… and that I should add a proper unit test for this :-D
