### ISSUE TITLE
config is not validated at all

### ISSUE THREAD

**Issue by shaardie** [opencast/pyCA#86]
I created a broken config file

    [agent]
    name             = 'pyca'
    update_frequency = 'string'  # this should be a integer

and started pyca. It still started normal without complaining about the broken config file and died later while trying to use an string as an int. Output:

    2017-03-15 14:55:36 INFO     [utils.py:90:get_service()] Endpoint for org.opencastproject.scheduler: https://octestallinone.virtuos.uos.de/recordings
    2017-03-15 14:55:36 INFO     [utils.py:90:get_service()] Endpoint for org.opencastproject.capture.admin: https://octestallinone.virtuos.uos.de/capture-admin
    2017-03-15 14:55:36 INFO     [utils.py:90:get_service()] Endpoint for org.opencastproject.capture.admin: https://octestallinone.virtuos.uos.de/capture-admin
    2017-03-15 14:55:36 INFO     [utils.py:90:get_service()] Endpoint for org.opencastproject.ingest: https://octestallinone.virtuos.uos.de/ingest
    2017-03-15 14:55:36 INFO     [schedule.py:106:control_loop()] No scheduled recording
    Process Process-1:
    Traceback (most recent call last):
      File "/usr/lib64/python3.5/multiprocessing/process.py", line 249, in _bootstrap
        self.run()
      File "/usr/lib64/python3.5/multiprocessing/process.py", line 93, in run
        self._target(*self._args, **self._kwargs)
      File "/tmp/env/lib/python3.5/site-packages/pyca-1.0.0-py3.5.egg/pyca/schedule.py", line 120, in run
        control_loop()
      File "/tmp/env/lib/python3.5/site-packages/pyca-1.0.0-py3.5.egg/pyca/schedule.py", line 108, in control_loop
        next_update = timestamp() + config()['agent']['update_frequency']
    TypeError: unsupported operand type(s) for +: 'int' and 'str'
    2017-03-15 14:55:36 INFO     [utils.py:90:get_service()] Endpoint for org.opencastproject.capture.admin: https://octestallinone.virtuos.uos.de/capture-admin
     Process Process-4:
    Traceback (most recent call last):
       File "/usr/lib64/python3.5/multiprocessing/process.py", line 249, in _bootstrap
        self.run()
      File "/usr/lib64/python3.5/multiprocessing/process.py", line 93, in run
        self._target(*self._args, **self._kwargs)
      File "/tmp/env/lib/python3.5/site-packages/pyca-1.0.0-py3.5.egg/pyca/agentstate.py", line 36, in run
        control_loop()
      File "/tmp/env/lib/python3.5/site-packages/pyca-1.0.0-py3.5.egg/pyca/agentstate.py", line 25, in control_loop
        next_update = timestamp() + config()['agent']['update_frequency']
    TypeError: unsupported operand type(s) for +: 'int' and 'str'

Also I printed content from `config.config()["agent"]["update_frequency"]` and got `string`.

So it seems the validator does not work as expected.

**Comment by lkiesow** [comment]
I vaguely remember someone telling me that returning stack traces is just fine ;-P

But the problem here is not the validation, which is executed just fine, but that the [return value of the validation is never checked](https://github.com/opencast/pyCA/blob/ac5eaf3a58f67c9b092ebf05a9ccf55ee1c2b06a/pyca/config.py#L54). A correct validation would simply return `True`. A broken `update_frequency` would cause a return value of `{'capture': True, 'ui': True, 'agent': {'cal_lookahead': True, 'name': True, 'database': True, 'update_frequency': False, 'ignore_timezone': True, 'backup_mode': True}, 'server': True}`

What would be your preferred and/or expected behavior?

**Comment by shaardie** [comment]
Yes and with a Traceback with a `BrokenConfigError` we would now only talk about a better user experience ;-P

I would not silently use the default values, but explicitly fail if the configuration is broken. Maybe raise the Exception mentioned above and catch it in the main for a better user experience.
